/*

    DKMapa is program for world data visualization for Tribal Wars game.
    Copyright (C) 2008-2009, Jiri Svoboda

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

/**
 * Application texts and messages class
 * 
 * @author Jiri Svoboda (http://jirkasuv.duch.cz/)
 */
// generated by txt2java.pl
public abstract class Messages {
  private static int language;
  private static final int EN = 0;
  private static final int CZ = 1;

  public static final int VERSION_NUMBER = 0;
  public static final int AUTHOR_NAME = 1;
  public static final int HOMEPAGE_URL = 2;
  public static final int NOTES = 3;
  public static final int ABANDONED_VILLAGE = 4;
  public static final int ABOUT = 5;
  public static final int ADD_ALLY = 6;
  public static final int ADD_THIS_ALLY = 7;
  public static final int ADD_THIS_TRIBE = 8;
  public static final int ADD_THIS_VILLAGE = 9;
  public static final int ADD_TRIBE = 10;
  public static final int ADD_VILLAGE = 11;
  public static final int ALLY = 12;
  public static final int ALLY_PL = 13;
  public static final int ALLY_WAS_DISCARDED = 14;
  public static final int ARCHER = 15;
  public static final int ASSIGN_COLOR_TO_THIS_ALLY = 16;
  public static final int ASSIGN_COLOR_TO_THIS_TRIBE = 17;
  public static final int ASSIGN_COLOR_TO_THIS_VILLAGE = 18;
  public static final int AUTOMATIC_MAP_REGENERATION = 19;
  public static final int AXEMAN = 20;
  public static final int CATAPULT = 21;
  public static final int CHANGE_COLOR_OF_ALLY = 22;
  public static final int CHANGE_COLOR_OF_TRIBE = 23;
  public static final int CHANGE_COLOR_OF_VILLAGE = 24;
  public static final int CLOSE = 25;
  public static final int CONTINENT_LETTER = 26;
  public static final int DATA_SOURCES = 27;
  public static final int DOWNLOADING_ALLYS = 28;
  public static final int DOWNLOADING_TRIBES = 29;
  public static final int DOWNLOADING_VILLAGES = 30;
  public static final int ENTER_ALLY_TAG_OR_ID = 31;
  public static final int ENTER_CONTINENT_NUMBER_OR_COORDS = 32;
  public static final int ENTER_TRIBE_NAME_OR_ID = 33;
  public static final int ENTER_VILLAGE_COORDS = 34;
  public static final int FILE = 35;
  public static final int FUNCTIONS = 36;
  public static final int GENERATE = 37;
  public static final int HEAVY_CAVALRY = 38;
  public static final int HELP = 39;
  public static final int HOMEPAGE = 40;
  public static final int IMPORTING_ALLYS = 41;
  public static final int IMPORTING_TRIBES = 42;
  public static final int IMPORTING_VILLAGES = 43;
  public static final int LIGHT_CAVALRY = 44;
  public static final int LIST2_AS_ALLIED = 45;
  public static final int LIST2_AS_ENEMIES = 46;
  public static final int LIST2_AS_NONAGGRESSION = 47;
  public static final int LIST2_NORMAL = 48;
  public static final int LIST3_AS_ALLIED = 49;
  public static final int LIST3_AS_ENEMIES = 50;
  public static final int LIST3_AS_NONAGGRESSION = 51;
  public static final int LIST3_NORMAL = 52;
  public static final int LISTS = 53;
  public static final int MERCHANT = 54;
  public static final int MOUNTED_ARCHER = 55;
  public static final int MOVE_TO_COORDS = 56;
  public static final int NEVER = 57;
  public static final int NO_ALLY = 58;
  public static final int NOBLEMAN = 59;
  public static final int NO_VILLAGE = 60;
  public static final int OK = 61;
  public static final int PALADIN = 62;
  public static final int POINTS = 63;
  public static final int QUIT = 64;
  public static final int RAM = 65;
  public static final int REMOVE_ALLY = 66;
  public static final int REMOVE_TRIBE = 67;
  public static final int REMOVE_VILLAGE = 68;
  public static final int SCOUT = 69;
  public static final int SEARCH = 70;
  public static final int SELECTED_VILLAGE = 71;
  public static final int SHOW_ABANDONED_VILLAGES = 72;
  public static final int SPEAR_FIGHTER = 73;
  public static final int SWORDSMAN = 74;
  public static final int TABLE_COLUMN_ADDRESS = 75;
  public static final int TABLE_COLUMN_SPEED = 76;
  public static final int TABLE_COLUMN_UNITSPEED = 77;
  public static final int TABLE_COLUMN_UPDATE = 78;
  public static final int TABLE_COLUMN_WORLDNAME = 79;
  public static final int TAG = 80;
  public static final int TRIBE_PL = 81;
  public static final int TRIBE = 82;
  public static final int TRIBE_WAS_DISCARDED = 83;
  public static final int TRIBEPOINTS_MAP = 84;
  public static final int UPDATE_WORLD_DATA = 85;
  public static final int VIEW_WORLD = 86;
  public static final int VILLAGE_PL = 87;
  public static final int VILLAGES = 88;
  public static final int VILLAGE = 89;
  public static final int VILLAGE_WAS_DISCARDED = 90;

  static final String[][] messages = {
    { "1.0", "1.0" }, // 0
    { "©2008-2009, Jiří Svoboda", "©2008-2009, Jiří Svoboda" }, // 1
    { "http://jirkasuv.duch.cz/java/DKMapa/", "http://jirkasuv.duch.cz/java/DKMapa/" }, // 2
    { "Free (GNU GPL v3 licensed) visualization program for Tribal Wars game.\nSpecial thanks to: Turgon, robotron.\nIn development process was used:\n- Debian GNU/Linux\n- Sun JDK 1.6.0\n- Geany (simple GTK+ IDE)", "Free (pod licencí GNU GPL v3) vizualizační program pro hru Divoké kmeny.\nZvláštní poděkování si zaslouží: Turgon, robotron.\nK vývoji byl použit:\n- Debian GNU/Linux\n- Sun JDK 1.6.0\n- Geany (jednoduché GTK+ IDE)" }, // 3
    { "Abandoned village", "Opuštěná vesnice" }, // 4
    { "About", "O programu" }, // 5
    { "Add ally", "Přidat kmen" }, // 6
    { "Add ally of this village", "Přidat kmen této vesnice" }, // 7
    { "Add player of this village", "Přidat hráče této vesnice" }, // 8
    { "Add this village", "Přidat tuto vesnici" }, // 9
    { "Add player", "Přidat hráče" }, // 10
    { "Add village", "Přidat vesnici" }, // 11
    { "Ally", "Kmen" }, // 12
    { "Allys", "Kmeny" }, // 13
    { "was discarded", "byla zrušena" }, // 14
    { "Arc", "Luč" }, // 15
    { "Assign color to this ally", "Přiřaď barvu tomuto kmenu" }, // 16
    { "Assign color to this player", "Přiřaď barvu tomuto hráči" }, // 17
    { "Assign color to this village", "Přiřaď barvu této vesnici" }, // 18
    { "Automatic map regeneration", "Automatické znovuvytváření mapy" }, // 19
    { "Axe", "Sek" }, // 20
    { "Cat", "Kat" }, // 21
    { "Change color of the ally", "Změnit barvu kmene" }, // 22
    { "Change color of the player", "Změnit barvu hráče" }, // 23
    { "Change color of the village", "Změnit barvu vesnice" }, // 24
    { "Close", "Zavřít" }, // 25
    { "C", "K" }, // 26
    { "Data sources", "Zdroje dat" }, // 27
    { "Downloading allys", "Stahuji kmeny" }, // 28
    { "Downloading players", "Stahuji hráče" }, // 29
    { "Downloading villages", "Stahuji vesnice" }, // 30
    { "Enter ally tag or id", "Zadejte tag nebo id kmene" }, // 31
    { "Enter continent number or coordinates", "Zadejte číslo kontinentu nebo souřadnice" }, // 32
    { "Enter player name or id", "Zadejte jméno nebo id hráče" }, // 33
    { "Enter village coordinates", "Zadejte souřadnice vesnice" }, // 34
    { "File", "Soubor" }, // 35
    { "Functions", "Funkce" }, // 36
    { "Generate", "Vytvoř" }, // 37
    { "HeC", "TěK" }, // 38
    { "Help", "Nápověda" }, // 39
    { "Homepage", "Domovská stránka" }, // 40
    { "Importing allys", "Importuji kmeny" }, // 41
    { "Importing players", "Importuji hráče" }, // 42
    { "Importing villages", "Importuji vesnice" }, // 43
    { "LiC", "LeK" }, // 44
    { "List 2 as allied", "Seznam 2 jako spojence" }, // 45
    { "List 2 as enemies", "Seznam 2 jako nepřátele" }, // 46
    { "List 2 as nonaggression", "Seznam 2 jako dohodu o neútočení" }, // 47
    { "List 2 normally", "Seznam 2 normálně" }, // 48
    { "List 3 as allied", "Seznam 3 jako spojence" }, // 49
    { "List 3 as enemies", "Seznam 3 jako nepřátele" }, // 50
    { "List 3 as nonaggression", "Seznam 3 jako dohodu o neútočení" }, // 51
    { "List 3 normally", "Seznam 3 normálně" }, // 52
    { "Lists", "Seznamy" }, // 53
    { "Mer", "Kup" }, // 54
    { "MoA", "LnK" }, // 55
    { "Move to coordinates", "Přesun na souřadnice" }, // 56
    { "never", "nikdy" }, // 57
    { "Not in any ally", "Není v žádném kmenu" }, // 58
    { "Nob", "Šle" }, // 59
    { "No village", "Žádná vesnice" }, // 60
    { "OK", "OK" }, // 61
    { "Pal", "Pal" }, // 62
    { "points", "bodů" }, // 63
    { "Quit", "Konec" }, // 64
    { "Ram", "Ber" }, // 65
    { "Remove ally", "Odebrat kmen" }, // 66
    { "Remove player", "Odebrat hráče" }, // 67
    { "Remove village", "Odebrat vesnici" }, // 68
    { "Sco", "Špe" }, // 69
    { "Search", "Hledej" }, // 70
    { "Selected village", "Vybraná vesnice" }, // 71
    { "Show abandoned villages", "Zobrazovat opuštěné vesnice" }, // 72
    { "SpF", "Kop" }, // 73
    { "Swo", "Šer" }, // 74
    { "World address", "Adresa světa" }, // 75
    { "Speed", "Rychlost" }, // 76
    { "Unit speed", "Rychlost jednotek" }, // 77
    { "Last update", "Aktualizace" }, // 78
    { "World name", "Jméno světa" }, // 79
    { "tag", "tag" }, // 80
    { "Players", "Hráči" }, // 81
    { "Player", "Hráč" }, // 82
    { "was discarded", "byl zrušen" }, // 83
    { "Playerpoints map", "Mapa bodů hráčů" }, // 84
    { "Update world data", "Aktualizovat data světa" }, // 85
    { "View world", "Prohlížet svět" }, // 86
    { "Villages", "Vesnice" }, // 87
    { "villages", "vesnic" }, // 88
    { "Village", "Vesnice" }, // 89
    { "was discarded", "byla zrušena" }, // 90
  };
// end of txt2java.pl


  public static void setLanguage(String lang) {
    if ((lang.compareTo("cs") == 0) || (lang.compareTo("sk") == 0)) {
      language = CZ;
    } else {
      language = EN;
    }
  }


  public static String getMessage(int message) {
    return messages[message][language];
  }


}
